databases:
  - name: kintai
    plan: free
    region: singapore
    databaseName: kintai
    user: kintai

services:
  - type: web
    plan: free
    region: singapore
    name: kintai
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn kintaiproject.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: kintai
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4