# Generated by Django 4.2.7 on 2023-12-10 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kintai', '0007_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kintaimodel',
            name='overpaycheck',
        ),
        migrations.RemoveField(
            model_name='kintaimodel',
            name='overtimealert',
        ),
    ]
