# Generated by Django 4.2.7 on 2024-01-10 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kintai', '0008_remove_kintaimodel_overpaycheck_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kintaimodel',
            name='overtime',
        ),
    ]
