# Generated by Django 4.2.7 on 2024-01-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kintai', '0009_remove_kintaimodel_overtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='kintaimodel',
            name='overtime',
            field=models.TimeField(default='0:00:00', verbose_name='残業時間'),
        ),
    ]
